print ("Hello world")
print ("hello again")
print ("i like typing this.")
print ("This is fun.")
print ('Yay ! printing.')
print ("i'd much rather you 'not' .")
print ('I "said" do not touch this.')
print ("______")
print ("another line")
#print ("make script print this line")
